## Main build
- branches:
    only:
      - master
      - /release/*
      - /hotfix/*
  skip_tags: true
  configuration:
    - Debug
    - Release
  version: 2.1.{build}-{branch}
  os:
  - Visual Studio 2015
  environment:
    installerVersion: 2.1.$(APPVEYOR_BUILD_NUMBER)
    containerURL:
      secure: 5ScgXebma0ZLFaW1DPgEdqis7MzXvPJL+c1O+f+gfkzqwAEzVmhk6ZmISlcgxCL3x3eawhSGYVzFy4Pap0dOGw==
    referenceFolder: References
  assembly_info:
    patch: true
    file: AssemblyVersion.cs
    assembly_version: "2.1.{build}"
    assembly_file_version: "2.1.{build}"
    assembly_informational_version: "{version}"
  before_build:
    - ps: GetReferenceFromContainer.ps1
    - nuget restore
  cache:
    - '%referenceFolder% -> appveyor.yml'
  build:
    project: TFS-Aggregator-2.sln
    # MSBuild verbosity level: quiet|minimal|normal|detailed
    verbosity: minimal
  test:
    assemblies:
      - UnitTests.Core.dll
  after_test:
    - msbuild build-installer.proj /p:Configuration=%CONFIGURATION% /p:SourceBranch=%APPVEYOR_REPO_BRANCH% /p:BuildVersion=%installerVersion%
  artifacts:
    - path: '*.zip'
    - path: '**\*.msi'
      name: MSI

## CI build
- branches:
    only:
      - develop
      - /feature/*
  skip_tags: true
  configuration:
    - Debug
  version: 2.1.{build}-{branch}
  os:
  - Visual Studio 2015
  environment:
    installerVersion: 2.1.$(APPVEYOR_BUILD_NUMBER)
    containerURL:
      secure: 5ScgXebma0ZLFaW1DPgEdqis7MzXvPJL+c1O+f+gfkzqwAEzVmhk6ZmISlcgxCL3x3eawhSGYVzFy4Pap0dOGw==
    referenceFolder: References
  assembly_info:
    patch: true
    file: AssemblyVersion.cs
    assembly_version: "2.1.{build}"
    assembly_file_version: "2.1.{build}"
    assembly_informational_version: "{version}"
  before_build:
    - ps: GetReferenceFromContainer.ps1
    - nuget restore
  cache:
    - '%referenceFolder% -> appveyor.yml'
  build:
    project: TFS-Aggregator-2.sln
    # MSBuild verbosity level: quiet|minimal|normal|detailed
    verbosity: minimal
  test:
    assemblies:
      - UnitTests.Core.dll
